### PR TITLE
Help href registry

### PR DESCRIPTION
**Pull request by simlei**
The functionality added is used as such:

**Register a help href**

```java
        String pluginId = "org.jcryptool.yourplugin"; // insert plugin name where to redirect the help button effect
        String helpHref = "/org.jcryptool.analysis.viterbi/$nl$/help/content/index.html"; // insert desired href
        org.jcryptool.core.commands.HelpHrefRegistry.getInstance().registerHrefFor(pluginId, helpHref);
```

### CODE REVIEW

**Comment by simlei** [comment]
I see a keystore change there caused by the inorder in commits that is maybe accidental; check the `.ksf` file in the changed files

**Comment by grthor** [comment]
Keystore change was intended, I added an AES 128bit for the introduction to have a key available.

**Comment by grthor** [comment]
I just tested it, and it works https://github.com/grthor/core/commit/c347ccf61ca3c8bbfa0b27248b9d99c83877cbac. It seems to be important to call the code in the ```createPartControl``` method. 

I first tried to call the code in the plugin start method https://github.com/grthor/core/commit/f79c0b498b1b10dc90c5e80af39d8b68a32dbe9f. This did not work. A comment in the method description would be nice.

**Comment by grthor** [comment]
Pushed the code to the core repo.

**Pull request merged**
